####################################################
#  User Definitions                                #
####################################################



PLATFORM=linux
#PLATFORM=A1
#PLATFORM=Chelsea
#PLATFORM=DRMe
#PLATFORM=Canmore
#PLATFORM=Valencia

#CFLAGS= -O2 -D__linux -DLINUX -DUNIX -DMTHREAD -D_REENTRANT -D_LINUX -DPRINT_LOG
#CFLAGS= -O2 -D_WIN32_ -D_WIN -D_WIN32_WCE -DMTHREAD -D_REENTRANT -DPRINT_LOG
#CFLAGS= -O2 -D__linux -DLINUX -DUNIX -DMTHREAD -D_REENTRANT -D_LINUX -DPRINT_LOG -D_WIN32_
#CFLAGS= -O2 -DMTHREAD -D_REENTRANT -DPRINT_LOG -D_WIN32_ -D_WIN

CFLAGS= -O2 -D__linux -DLINUX -DUNIX -DMTHREAD -D_REENTRANT -D_LINUX -DPRINT_LOG  -g -D_DRMLOG_DISABLE -lstdc++



HOST_OS := $(shell uname -s | tr A-Z a-z | cut -d'_' -f1)
ifeq ($(HOST_OS),mingw32)
	CFLAGS+= -D_WIN
endif
####################################################
#  Options                                         #
####################################################
ifeq ($(PLATFORM), linux)
	CROSS_COMPILE=
	
	CFLAGS+= -Wall -Wextra -Wcast-align -Wno-unused-parameter -Wshadow -Wwrite-strings -Wcast-qual -fstrict-aliasing -fsigned-char
	CFLAGS+= -ffunction-sections -fdata-sections -fPIC  -Wstrict-prototypes -fpermissive
	
	
else ifeq ($(PLATFORM), A1)	
	CROSS_COMPILE=arm_v6_vfp_le-

	CFLAGS+= -Wall -Wextra -Wcast-align -Wno-unused-parameter -Wshadow -Wwrite-strings -Wcast-qual -fstrict-aliasing -fstrict-overflow -fsigned-char
	CFLAGS+= -ffunction-sections -fdata-sections -Werror -Wstrict-prototypes 
	
else ifeq ($(PLATFORM), Chelsea)	
	CROSS_COMPILE=arm_v6_vfp_le-

	CFLAGS+= -Wall -Wextra -Wcast-align -Wno-unused-parameter -Wshadow -Wwrite-strings -Wcast-qual -fstrict-aliasing -fstrict-overflow -fsigned-char
	CFLAGS+= -ffunction-sections -fdata-sections -Werror -Wstrict-prototypes 

else ifeq ($(PLATFORM), Valencia)	
	CROSS_COMPILE=arm_v7_vfp_le-

	CFLAGS+= -Wall -Wextra -Wcast-align -Wno-unused-parameter -Wshadow -Wwrite-strings -Wcast-qual -fstrict-aliasing -fstrict-overflow -fsigned-char
	CFLAGS+= -ffunction-sections -fdata-sections -Werror -Wstrict-prototypes 

else ifeq ($(PLATFORM), DRMe)
	CROSS_COMPILE=arm-linux-

	CFLAGS+= -Wall -Wextra -Wcast-align -Wno-unused-parameter -Wshadow -Wwrite-strings -Wcast-qual -fstrict-aliasing -fsigned-char
	CFLAGS+= -ffunction-sections -fdata-sections -Werror -Wstrict-prototypes

else ifeq ($(PLATFORM), Canmore)
        CROSS_COMPILE=i686-cm-linux-

        CFLAGS+= -Wall -Wextra -Wcast-align -Wno-unused-parameter -Wshadow -Wwrite-strings -Wcast-qual -fstrict-aliasing -fsigned-char
        CFLAGS+= -ffunction-sections -fdata-sections -Werror -Wstrict-prototypes
endif

CRYPTOCORE_HOME=..
