name: Build Makefile (Ubuntu & ARM)

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        include:
          - architecture: x86_64
            apt_packages: build-essential
            make_args: "LOCAL_LFLAGS='-Wl,--allow-multiple-definition'"

          - architecture: arm64
            apt_packages: gcc-aarch64-linux-gnu g++-aarch64-linux-gnu
            make_args: "CC=aarch64-linux-gnu-gcc CXX=aarch64-linux-gnu-g++ LOCAL_LFLAGS='-Wl,--allow-multiple-definition'"

    steps:
    - name: Checkout do código
      uses: actions/checkout@v4

    - name: Instalar toolchains de compilação
      run: |
        sudo apt-get update
        sudo apt-get install -y ${{ matrix.apt_packages }}

    - name: Configurar Multiarch e Instalar (Apenas para Cross-compile)
      run: |
        sudo dpkg --add-architecture arm64
        sudo sed -i 's/deb http/deb [arch=amd64,i386] http/g' /etc/apt/sources.list
        sudo bash -c 'cat <<EOF > /etc/apt/sources.list.d/arm-cross-compile-sources.list
        deb [arch=arm64] http://ports.ubuntu.com/ubuntu-ports jammy main restricted universe multiverse
        deb [arch=arm64] http://ports.ubuntu.com/ubuntu-ports jammy-updates main restricted universe multiverse
        EOF'
        sudo apt-get update
        sudo apt-get install -y gcc-aarch64-linux-gnu g++-aarch64-linux-gnu libssl-dev:arm64
        

    - name: Compilar com Makefile
      env:
        HOST_OS: linux
      run: make ${{ matrix.make_args }}
      working-directory: ${{ github.workspace }}

    # --- NOVO PASSO AQUI ---
    - name: Salvar binário (Upload Artifact)
      uses: actions/upload-artifact@v4
      with:
        # Usa a variável da matriz para dar um nome diferente para o arquivo do PC e do ARM
        name: executavel-sdb-${{ matrix.architecture }}
        
        # COLOQUE AQUI O NOME DO BINÁRIO QUE O MAKEFILE GERA (ex: sdb, out/sdb, etc)
        path: ./bin/sdb
