name: Build Makefile (Ubuntu & ARM)

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    # O runner será sempre o Ubuntu, mas compilaremos para diferentes arquiteturas
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        include:
          # 1. Compilação nativa para Ubuntu (x86_64)
          - architecture: x86_64
            apt_packages: build-essential
            make_args: "LDFLAGS='-Wl,--allow-multiple-definition'"

          # 2. Compilação cruzada para ARM64 (AArch64)
          #- architecture: arm64
           # apt_packages: gcc-aarch64-linux-gnu g++-aarch64-linux-gnu
           # make_args: "CC=aarch64-linux-gnu-gcc CXX=aarch64-linux-gnu-g++"

    steps:
    - name: Checkout do código
      uses: actions/checkout@v4

    - name: Instalar toolchains de compilação
      run: |
        sudo apt-get update
        sudo apt-get install -y ${{ matrix.apt_packages }}

    - name: Compilar com Makefile
      # O comando make será executado na raiz do repositório
      # Para ARM64, ele passará os compiladores específicos (CC e CXX) como argumento
      run: make HOST_OS=linux ${{ matrix.make_args }}
      working-directory: ${{ github.workspace }}
