name: Build Makefile (Ubuntu & ARM)

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    # Em vez de fixar no Ubuntu padrão, usamos a variável da matriz
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        include:
          # PC normal (x86_64)
          - architecture: x86_64
            os: ubuntu-latest
          
          # Máquina ARM nativa do GitHub
          - architecture: arm64
            os: ubuntu-24.04-arm

    steps:
    - name: Checkout do código
      uses: actions/checkout@v4

    - name: Instalar dependências
      # Agora a instalação é IGUAL para os dois! 
      # O libssl-dev fornece o libcrypto que faltava
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential libssl-dev

    - name: Compilar com Makefile
      env:
        HOST_OS: linux
      # Não precisamos mais do CC=aarch64... porque o Ubuntu arm já usa o compilador certo!
      run: make LOCAL_LFLAGS='-Wl,--allow-multiple-definition'
      working-directory: ${{ github.workspace }}

    - name: Salvar binário (Upload Artifact)
      uses: actions/upload-artifact@v4
      with:
        name: executavel-sdb-${{ matrix.architecture }}
        path: sdb
    - name: Compilar com Makefile
      # O comando make será executado na raiz do repositório
      # Para ARM64, ele passará os compiladores específicos (CC e CXX) como argumento
      run: make HOST_OS=linux ${{ matrix.make_args }}
      working-directory: ${{ github.workspace }}

      # --- NOVO PASSO AQUI ---
    - name: Salvar binário (Upload Artifact)
      uses: actions/upload-artifact@v4
      with:
        # Usa a variável da matriz para dar um nome diferente para o arquivo do PC e do ARM
        name: executavel-sdb-${{ matrix.architecture }}
        
        # COLOQUE AQUI O NOME DO BINÁRIO QUE O MAKEFILE GERA (ex: sdb, out/sdb, etc)
        path: ./bin/sdb
